README.md

Currently points to lightningnetwork/lnd.

Fix umbrel-middleware link in readme

---

Dockerfile

Reduces final image size from 414MB to 169MB by using a disposable build stage to build the project.
```
$ docker images umbrel-dashboard
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
umbrel-dashboard    slim                ffbb89f25bd6        6 minutes ago       169MB
umbrel-dashboard    master              9a19d09efd79        50 minutes ago      414MB
```
It is possible to get a smaller ~100MB image by using `debian:buster-slim` as a base and manually pulling in only `node` and `http-server` into the image.
However this gives less cumulative advantage. Even though `debian:buster-slim`+`node` is smaller than `node:12.16.3-buster-slim`, it will result in duplicate Node.js layers for each Node.js Docker image.
If we use the slightly larger …

Add docker build stage and use Debian Buster as base

---

.dockerignore

This will reduce the amount of fluff we add to the build.
It also means changing the Dockerfile won't invalidate almost the entire build since it was previously invalidating everything below `COPY. .`.
I also excluded `node_modules` so we can be sure we get a fresh install of dependencies inside the image.

Add unneeded files to .dockerignore

---

src/App.vue
src/components/Shutdown.vue
src/helpers/delay.js
src/store/modules/system.js
src/views/Settings.vue

Related:
- https://github.com/getumbrel/umbrel/pull/28
- https://github.com/getumbrel/umbrel-manager/pull/21
I've just stubbed out the API for now.
Would be good to get some feedback on the code. I've not used Vue before so let me know if there's a better way to do anything.
The reboot modal can't be closed while the device is rebooting to keep the user there until everything is running again.
Also the UI fades out on shutdown to make sure they don't try to interact with the UI while Umbrel is down.
Demo:

Add power cycle functionality

---

src/store/modules/system.js

Pi is sloooow. The dashboard optimistically shows that the reboot is complete after 30s of inactivity, even though it can take a few more seconds for the services to get back up.

Wait 60s for reboot

---

src/views/Start.vue

Should be "Tor Browser" not "Tor browser".
Also we could probably just drop the word "browser" completely and have:
>Even when you're not on your home network, you can access your Umbrel using Tor on the following URL
Tor Browser is not technically a requirement, only Tor. Any browser can be configured to use Tor.

Fix Tor Browser capitalisation

---

src/views/Lightning.vue

Since it's crypted, it's not obvious that it's the node's alias. So it doesn't make any sense to show it.

Remove alias from node info modal

---

src/App.vue

If the page is refreshed, it might not load again as the server could be down while the Docker containers are restarting, leading the user to falsely believe that something went wrong or their node went down.

Add a warning to not refresh the page while updating/rebooting/shutting down

---

.gitignore
README.md

This way changes to the local dev environment do not change `.env`, which is part of the version control.
It gives an easy way to override the dev settings without messing with otherwise defined env vars.

Document and ignore local dev env file

---

src/views/Bitcoin.vue
src/views/Lightning.vue
src/views/Settings.vue

This allows user to filter and view logs for only bitcoin and lnd, and is especially useful for us when trying to fetch logs for a either of these services without having middleware/manager spam the entire log stream. 
The logs in settings have also been moved to the 3-dot menu for consistency.

Filter logs for bitcoin and lnd

---

src/views/Lightning.vue

It's redundant, helps no one, and ends up confusing users. Users who still need it for whatever reason can get it from the peer address itself.

Remove public key from lnd info modal

---

src/views/Settings.vue

Clutter-free. Allows us to add more settings to this new "Account" card later, eg. change name, view seed, etc.

Move change password inputs to a dedicated modal

---

src/components/CardWidget.vue
src/views/Bitcoin.vue
src/views/Lightning.vue

closes #132 
Tried black at first so they really stood out, but I think the "text-muted" color of `#6c757d` already in use elsewhere in the app looks a little better.

Improve visibility of ellipsis

---

src/views/Lightning.vue

Resolves #227. In case the hidden service url isn't available, it falls back to pubkey (eg. on a fresh start).

Show peer address in the QR code instead of pubkey

---

src/components/Utility/Seed.vue
src/views/Start.vue

The first two commits should be uncontroversial: When entering the seed the Enter key allows to proceed to the next word (in addition to clicking the button right to the input). 
While testing I found a case where navigating further is possible without completing the steps. If one goes to word 24 of thee seed page, uses the back button and then chooses to recover: Now the Next button is immediately enabled. The second commit fixes this.
The third commit can be considered optional and I can remove it from the PR if wanted: I found it to be confusing having the Next button present on the Recover page, especially since there are also the navigation buttons left and right to the input. Also the disabled state didn't seem obvious, so that I tried several times to go further using the Next …

Seed improvements

---

package.json
src/components/BitcoinWallet.vue
src/components/Channels/Manage.vue
src/components/Channels/Open.vue
src/components/Utility/FeeSelector.vue

This PR makes it possible for the user to select a custom fee (denoted in sat/vB) for channel open and bitcoin withdrawal transactions.
Closes https://github.com/getumbrel/umbrel/issues/266

Set custom fee for on-chain transactions

---

src/components/Utility/FeeSelector.vue

For example, for the following fee outputs:
```js
{
"fast": { "feeSat": "15795", "feerateSatPerByte": "111" },
"normal": { "feeSat": "15042", "feerateSatPerByte": "105" },
"slow": { "feeSat": "13733", "feerateSatPerByte": "96" },
"cheapest": { "code": "FEE_RATE_TOO_LOW", "text": "Mempool reject low fee transaction." }
}
```
The default fee slider would be:

Remove errored fee options from default fee slider

---

Dockerfile.dev

This adds an alternative Dockerfile to be used during development that support HMR.

Add development Dockerfile for umbrel-dev

---

vue.config.js

This is required to allow umbrel-dev access to the HMR WebSocket.

Add umbrel-dev.local as an allowed host to dev server

---

src/components/Utility/QrCode.vue

The logo was quite big which meant the scan error rate was very high. In Android QRs with a small amount of data such as Electrum or Bitcoin Core P2P connection details were practically impossible to scan.

Reduce QR logo size

---

Dockerfile.dev

We're polling for fs changes in the dev dockerfile instead of listening for fs events so it works reliable across VirtualBox/Docker volumes.
However in some cases (not always, not sure why) this results in really high CPU utilisation.
Setting the poll interval to 1000ms up from the default 100ms seems to alleviate this and is still fast enough for live reload.

Set fs poll interval to 1 second in dev Dockerfile

---

src/global-styles/custom.scss
src/layouts/DashboardLayout.vue

Release notes can now have `\n` which will be respected in the view. It's a non-breaking change so previous versions of dashboard will just disregard `\n` completely without rendering or supporting it.

Support newlines in release notes

---

src/App.vue

After an unclean shutdown sometimes Bitcoin Core needs to roll back blocks which can take quite a while. Sometimes users lose patience with the "Loading Bitcoin Core..." message and think something is stuck and just pull the power. This can (and has) caused more serious issues like filesystem corruption.
This change reassures the user if Bitcoin Core hasn't loaded after 10 seconds that this can sometimes take a while and asks them not to pull the power.

Warn users not to restart on slow Bitcoin startup

---

src/components/Blockchain.vue
src/store/modules/bitcoin.js

fixes #195 
Improve the performance of the block animation by:
- Limiting blocks in memory to 6 (that's all we should need for the animation)

Only render latest 6 block in DOM 

---

src/components/AuthenticatedVerticalNavbar.vue

Just a tiny CSS fix so that sidebar can stay scrollable on small screens.
Currently, without `overflow-y: auto` on `.nav-vertical`, App store and other options at the bottom of the sidebar remain inaccessible on small screens.

Make .nav-vertical scrollable for screens with small height

---

src/components/BitcoinWallet.vue

- Use the mempool app if installed.
- If mempool isn't installed, use btc-rpc-explorer app.
- If btc-rpc-explorer isn't installed, warn the user before opening the public mempool.space.
Resolves https://github.com/getumbrel/umbrel/issues/488, resolves https://github.com/getumbrel/umbrel/issues/435, resolves https://github.com/getumbrel/umbrel-dashboard/issues/290, resolves https://github.com/getumbrel/umbrel-dashboard/issues/164.

Use a local explorer app instead of mempool.space

---

Dockerfile

When using 404.html page as a fallback, `http-server` still returns a 404 status for `vue-router` pages.
This PR replaces `http-server` with [`serve`](https://www.npmjs.com/package/serve) that supports serving single page application.

Use `serve`

---

public/index.html

Resolves https://github.com/getumbrel/umbrel/issues/639
This disables setting the referrer header in HTTP requests. Setting the referrer is a privacy issue since it leaks the hidden service address to 3rd parties when visiting an external link.

Disable referrer in HTTP requests

---

src/store/modules/lightning.js
src/views/Login.vue

Related:
- https://github.com/getumbrel/umbrel-manager/pull/85
- https://github.com/getumbrel/umbrel-middleware/pull/82
This is no longer needed since we now auto unlock the LND wallet at boot time: https://github.com/getumbrel/umbrel-middleware/pull/82

Remove LND unlock logic from dashboard

---

src/views/Bitcoin.vue
src/views/Lightning.vue
src/views/Settings.vue

The /logs page has been removed in https://github.com/getumbrel/umbrel/pull/718

Remove links to /logs page from dashboard

---

src/App.vue

Resolves: https://github.com/getumbrel/umbrel/issues/728
This detects when Umbrel is running in an iframe and shows an error instead of rendering the application to prevent clickjacking attacks as described in the above issue.
Thanks @Rubinoussoren!
**Note:** A more robust solution would be to serve the app with the `X-Frame-Options: DENY` HTTP header instead of relying on JavaScript to detect the existence of an iframe like in this PR. We should do both, but at the moment we don't have a proper server configuration committed to the dashboard codebase and just pull in a simple static server to the Docker image so this is fine for now.

Prevent Umbrel from running in an iframe

---

src/views/Start.vue

Now that the dashboard doesn't require LND or Bitcoin Core to be ready before loading the UI (https://github.com/getumbrel/umbrel-dashboard/pull/327) the user creation process can be ready before LND, which errors when it requests a seed phrase.
This PR adds a simple check, only in the user creation view, that shows the user a loading animation until LND is ready.

Don't allow user creation process before LND is ready

---

src/views/Start.vue

Without this change the user can click the loading button to proceed with the setup process before LND is ready. This should have been included as part of https://github.com/getumbrel/umbrel-dashboard/pull/337.

Disable click on setup loading button

---

CONTRIBUTING.md
LICENSE.md
README.md

This PR switches Umbrel Dashboard’s current license from CC-NC-ND-4.0 to the PolyForm Noncommercial 1.0.0 license, a much more permissive and open license, and adds a CONTRIBUTING.md.
Full announcement explaining this license change can be found on [our blog](https://blog.getumbrel.com/everything-you-need-to-know-about-umbrels-new-license-f9807203a57e) and a Licensing FAQ can be found [here](https://github.com/getumbrel/umbrel/wiki/License-FAQ).

Switch to the PolyForm Noncommercial License

---

src/global-styles/_variables.scss

System fonts on Windows and Ubuntu look terrible. This PR changes the font to Roboto on non-Apple installs, the closest looking font to San Francisco typeface.

Use Roboto font on non-Apple devices

---

src/components/ConnectWallet/Wallets/Sparrow.vue

When setting up Sparrow to connect to Umbrel, there's a small typo on type of server. 
This PR fixes that.

Fix small typo

---

src/views/Start.vue

After https://github.com/getumbrel/umbrel-dashboard/pull/398, `"user/getSeed"` action now accepts a JSON parameter, which is why it errored out if expected keys were missing.

Seed setup hotfix

---

src/components/InstalledApp.vue

Previously, the code used http://${window.location.hostname} to build
the base URL for checking the status of an app. Now it uses
${window.location.origin}.
In my case, I have set up nginx as a reverse proxy in order to use TLS
encryption for my node. I am accessing Umbrel via https:// now. As a
result, the functionality to check the status of services was not
working due to the browser blocking mixed content requests.
I have not actually tested this code, as I don't have a development environment set up for Umbrel. I'm hoping someone else can test or this is straightforward enough to include.

Use window.location.origin to create InstalledApp url

---

src/views/Login/Login.vue

As described in #429 
`$nextTick` was used, otherwise the query selector is too fast for the DOM
`$el.querySelector('input')` is used on `$refs.password`, because the `<input-password>` tag splits into a `<div>` and `<input>` tag where `ref="password"` is put on the `<div>` tag, while `select()` is needed on the `<input>` tag

Select password input field on login page load and wrong password input

---

src/components/Dock.vue
src/components/DockApp.vue

This pull request proposes changes that fix the dock wobble issue noted by @Sun0fABeach in Issue #434, while preserving the margins within the dock. This works on both desktop and mobile (when the dock is mounted to the left). 
https://user-images.githubusercontent.com/85373263/193135690-f97b9568-f880-4f2b-84d8-c157572b0a66.mp4
I tried not to change the underlying html or javascript too much, and instead focused on a css solution. This could work as a short-term solution to the dock wobble issue; however, I think a longer-term solution would be to rewrite some of the html in `Dock.vue` and `DockApp.vue` so that the css can be simplified.
**Some notes about the changes (not exhaustive):**
- Replaced margin property with padding for .dock-app-container. Removed height/width properties from …

Fix dock hover wobble #2
