getumbrel/umbrel-dashboard

src/components/Channels/Channel.vue, src/components/Channels/List.vue, src/components/Channels/Manage.vue, src/store/modules/lightning.js
=> Use pre-fetched remote alias(es) in channel details/list

src/App.vue
=> Refined loading bar percent

src/components/Utility/Seed.vue, src/views/Start.vue
=> Recover from existing seed

.github/workflows/on-push.yml, README.md
=> PR workflow test

src/views/Dashboard.vue, src/views/Settings.vue
A cleaner, new greeting message on the dashboard
=> Greeting message

src/components/Channels/Manage.vue
=> Hide commit fee when channel isn't online

src/components/BitcoinWallet.vue, src/components/LightningWallet.vue, src/components/Utility/InputCopy.vue, src/views/Lightning.vue
=> Copy button consistent click

src/App.vue, src/store/modules/lightning.js
=> Check if logged in inside loading view

src/components/CardWidget.vue, src/helpers/api.js, src/views/Bitcoin.vue, src/views/Lightning.vue
=> Download channel backup

src/store/modules/lightning.js, src/views/Lightning.vue
=> Show node uri and alias

src/components/Blockchain.vue, src/store/modules/bitcoin.js
=> Add new blocks to the chain

.env, src/views/Lightning.vue
=> Node info loading view

src/views/Start.vue
=> Don't be too reckless

src/global-styles/custom.scss
=> Fix fat cards on ultra-wide displays

src/components/ToggleSwitch.vue, src/views/Settings.vue
=> Disable Tor switches

src/views/Start.vue
=> Craig Wright is a fraud

src/App.vue, src/components/Shutdown.vue, src/store/modules/system.js, src/views/Settings.vue
=> Poll to notify user once the shutdown/reboot is complete

src/views/Start.vue
=> Replace check icons with warning icons on the onboarding disclaimer

src/views/Start.vue
=> Make it clear that Umbrel can be used right away without waiting for the sync to complete

src/views/Start.vue
Consistent with the fade animation on the login button
=> Replace ugly spinner on "Go to dashboard" with a clean fade animation

src/components/Seed.vue, src/views/Lightning.vue, src/views/Settings.vue
The end-user doesn't know that the seed is generated by LND, so he wouldn't expect it on the lightning page. For him, the seed is generated by Umbrel so it should be on the settings page.
=> Move seed phrase to the settings page

src/views/Bitcoin.vue, src/views/Lightning.vue
=> Remove non-functional menus/buttons

src/store/modules/bitcoin.js, src/views/Bitcoin.vue
=> Show Bitcoin's P2P hidden service URL

src/App.vue
=> Show progress bar loading status

src/views/Settings.vue
=> Add backup toggle-switch to the settings page

src/views/Settings.vue
=> Add a "learn more" link to backups

src/components/BitcoinWallet.vue, src/components/Channels/Open.vue, src/store/modules/bitcoin.js
=> Show channel open errors for only the highest fee

src/views/Start.vue
[Issue](https://twitter.com/getumbrel/status/1301405950805385221)
=> Nsync not nsynch - due to consensus

.env, src/store/modules/system.js, src/views/Settings.vue
Fetch and show the last successful/failed backup status with timestamp on the settings page.
=> Show backup status in settings

src/views/Settings.vue
=> Move seed to account card

src/views/Settings.vue
=> Move backup toggle to account card

src/components/Utility/CountUp.vue
=> Adds CSS to wrap long balances to next line

src/components/Channels/Open.vue, src/views/Lightning.vue
=> Rename peer address => lightning address

src/components/BitcoinConnectWallet.vue, src/store/modules/bitcoin.js, src/views/Bitcoin.vue
This PR adds the UI required for https://github.com/getumbrel/umbrel/issues/247.
=> Show RPC wallets and info in Bitcoin wallet connector

src/components/BitcoinWallet.vue
Also moved to the right of the "Amount" label so it plays nicely with the layout changes in https://github.com/getumbrel/umbrel-dashboard/pull/236
=> Rename withdraw all funds => Max

src/store/modules/bitcoin.js
Related: https://github.com/getumbrel/umbrel-manager/pull/53#issue-497325871
=> Fetch Bitcoin price from Umbrel Manager API

src/components/Channels/List.vue
We can't have fun staying poor
=> Retire Lightning channel offer

src/components/CardWidget.vue, src/views/AppStore.vue
=> Add app dev card to the app store

src/components/ConnectWallet/ConnectionDetails.vue, src/components/ConnectWallet/Wallets/BitBoxApp.vue, src/components/ConnectWallet/Wallets/BitcoinCoreP2P.vue, src/components/ConnectWallet/Wallets/BitcoinCoreRPC.vue, src/components/ConnectWallet/Wallets/BlockstreamGreen.vue, src/components/ConnectWallet/Wallets/BlueWalletAndroid.vue, src/components/ConnectWallet/Wallets/ElectrumAndroid.vue, src/components/ConnectWallet/Wallets/ElectrumDesktop.vue, src/components/ConnectWallet/Wallets/ElectrumServer.vue, src/components/ConnectWallet/Wallets/FullyNoded.vue, src/components/ConnectWallet/Wallets/LNDConnectGRPCLocal.vue, src/components/ConnectWallet/Wallets/LNDConnectGRPCTor.vue, src/components/ConnectWallet/Wallets/LNDConnectRESTLocal.vue, src/components/ConnectWallet/Wallets/LNDConnectRESTTor.vue, src/components/ConnectWallet/Wallets/Phoenix.vue, src/components/ConnectWallet/Wallets/Sparrow.vue, src/components/ConnectWallet/Wallets/SpecterDesktop.vue, src/components/ConnectWallet/Wallets/Wasabi.vue, src/components/ConnectWallet/Wallets/ZapAndroid.vue, src/components/ConnectWallet/Wallets/ZapDesktop.vue, src/components/ConnectWallet/Wallets/ZapiOS.vue, src/components/ConnectWallet/Wallets/ZeusAndroid.vue, src/components/ConnectWallet/Wallets/ZeusiOS.vue, src/global-styles/custom.scss
=> Add wait time note in wallet connector

src/components/ConnectWallet/Wallets/ElectrumDesktop.vue
It takes a few seconds to reflect the changes, it looks like it hasn't worked if you don't wait for a bit.
=> Mention Electrum dot can take a while to change colour

src/components/LightningWallet.vue
=> Center align Lightning QR Code

src/App.vue, src/helpers/api.js, src/store/modules/bitcoin.js, src/store/modules/lightning.js, src/views/Login.vue
Depends on: https://github.com/getumbrel/umbrel-dashboard/pull/326
Currently Bitcoin and Lightning must be fully functional for the login process to complete.
This PR removes that dependency and gives the user immediate access to the dashboard after logging in. Bitcoin Core and LND can be loading or even hanging in the background and the user will still be able to access and use the dashboard.
=> Decouple Bitcoin and Lightning from login

src/views/Settings.vue
Debug => Troubleshoot, and an complete dark modal for the logs.
=> Troubleshooting UI improvements

src/App.vue
Not needed anymore after decoupling from LND and Bitcoin Core.
=> Remove loading text

src/views/Settings.vue
=> Remove requirement to login once after restart

src/components/Blockchain.vue
1 transaction
1748 transactions
=> Remove "s" at transactions if block has 1 transaction

src/components/ConnectWallet/Wallets/LilyWallet.vue, src/router/index.js, src/views/ConnectWallet.vue
Replaces https://github.com/getumbrel/umbrel-dashboard/pull/331 with some minor amendments added.
=> Add Lily Wallet connection details

src/store/modules/system.js
Related: https://github.com/getumbrel/umbrel/pull/748
Show the development build version if it's set.
=> Show build version if set

src/layouts/DashboardLayout.vue
The forums should be the main place for discussion and questions.
=> Link to community forum instead of Telegram chat

src/layouts/DashboardLayout.vue, src/store/modules/system.js
This PR gives the user visual feedback in the UI if their device is running out of memory.
=> Show alert if device is running out of memory

src/components/ConnectWallet/ConnectionDetails.vue
Resolves https://github.com/getumbrel/umbrel/issues/800
=> Inform user they need to wait for Electrum server to index

src/components/Widgets/TemperatureWidget.vue
=> Corrected  typo Celcius to Celsius

src/components/InstalledApp.vue, src/global-styles/custom.scss, src/views/AppStoreApp.vue
This PR adds a loading state for apps that aren't yet online by polling their URLs in the browser and checking against a `200` HTTP response.
=> Add loading state for offline apps

src/components/ToggleSwitch.vue, src/components/Utility/InputOtpToken.vue, src/store/modules/user.js, src/views/Login.vue, src/views/Settings.vue
This PR adds support for 2FA to the front-end with a new 6-digit input for 2FA tokens, toggle to enable/disable 2FA, and 2FA check on login.
API: https://github.com/getumbrel/umbrel-manager/pull/112
=> Add support for 2FA

src/components/Seed.vue, src/components/Utility/InputOtpToken.vue, src/store/modules/user.js, src/views/Settings.vue
This PR adds 2FA to view seed and change password for users who've enabled 2FA.
=> Add 2FA to view seed and change password

src/components/ConnectWallet/Wallets/Nunchuk.vue, src/components/ConnectWallet/Wallets/NunchukDesktop.vue, src/router/index.js, src/views/ConnectWallet.vue
Adds connection instructions for Nunchuk Wallet Desktop (using Electrum)
=> Add Nunchuk (Desktop) connection details

src/components/Channels/Manage.vue
Closes #414.
Thanks @bitpaint!
=> Fix typo in the warning message for closing channel
